# Generated by Django 4.1.13 on 2024-05-21 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_organization_employee_member_organization_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='id_contact',
        ),
        migrations.AddField(
            model_name='organization',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.DeleteModel(
            name='ContactOrganization',
        ),
    ]
