# Generated by Django 4.1.13 on 2024-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='identification',
            field=models.CharField(max_length=15),
        ),
    ]
