# Generated by Django 4.1.13 on 2024-05-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_identification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='organization',
            new_name='member_organization',
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='password', max_length=30),
            preserve_default=False,
        ),
    ]
