# Generated by Django 4.1.13 on 2024-05-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role_name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='roles',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.CharField(choices=[('Admin', 'Administrar roles y usuarios'), ('Coordinador', 'Administrar roles, proyectos y tareas'), ('Empleado', 'Interactuar con la aplicacion')], default=[], max_length=50),
            preserve_default=False,
        ),
    ]
