# Generated by Django 4.1.13 on 2024-05-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_rename_name_role_role_name_remove_role_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.CharField(choices=[('admin', 'Administrar roles y usuarios'), ('coordinator', 'Administrar roles, proyectos y tareas'), ('employee', 'Interactuar con la aplicacion')], max_length=50),
        ),
    ]
