# Generated by Django 4.1.13 on 2024-05-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_name_task_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='proyecto_aociado',
            new_name='proyecto_asociado',
        ),
    ]
