# Generated by Django 4.1.13 on 2024-05-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_comments_task_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='empleado_asignado',
            new_name='associated_employee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='proyecto_asociado',
            new_name='tied_project',
        ),
    ]
