# Generated by Django 4.1.13 on 2024-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_empleado_asignado_task_associated_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'pendiente'), ('En Progreso', 'en_progreso'), ('Completada', 'completada')], max_length=50),
        ),
    ]
