# Generated by Django 4.1.13 on 2024-05-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('task', '0001_initial'),
        ('project', '0002_rename_name_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(to='task.task'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='participants',
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(to='employee.employee'),
        ),
    ]
