# Generated by Django 4.1.13 on 2024-05-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_tasks_remove_project_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
    ]
