# Generated by Django 4.1.13 on 2024-05-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_state'),
        ('project', '0004_remove_project_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(to='task.task'),
        ),
    ]
