# Generated by Django 4.1.13 on 2024-05-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='time',
            new_name='meetTime',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='name',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='participants',
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(to='employee.employee'),
        ),
    ]
