# Generated by Django 4.1.13 on 2024-05-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_rename_time_meeting_meettime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meetTime',
            new_name='meet_time',
        ),
    ]
